using System.Diagnostics;

namespace Crawler;

public enum InteractionMode {
    Disabled,
    Menu,
    Immediate, // Perform now
}

/// <summary>
/// Concrete action that can be performed. Generated by IProposal.
/// </summary>
public interface IInteraction {
    /// <summary>Can this interaction be performed right now?</summary>
    InteractionMode PerformMode(string args = "");

    /// <summary>Execute the interaction. Returns AP cost (0 for instant).</summary>
    int Perform(string args = "");

    /// <summary>Display message for viewer. Primarily used for customs and extortion demands.</summary>
    string? MessageFor(IActor viewer);

    /// <summary>Display description for menus</summary>
    string Description { get; }

    /// <summary>Shortcut key code (e.g., "T" for trade, "DA" for demand accept)</summary>
    string OptionCode { get; }
}

// Simple consequence: mark as hostile
public record HostilityInteraction(IActor Agent, IActor Subject, string Reason): IInteraction {
    public InteractionMode PerformMode(string args = "") => InteractionMode.Menu;
    public int Perform(string args = "") {
        Agent.To(Subject).Hostile = true;
        Subject.To(Agent).Hostile = true;
        Agent.Message($"{Subject.Name} {Reason}. You are now hostile.");
        Subject.Message($"{Agent.Name} turns hostile because you {Reason.Replace("refuses", "refused")}!");
        Subject.Supplies[Commodity.Morale] -= 2;
        return 1;
    }
    public string? MessageFor(IActor viewer) => null;
    public string Description => $"Turn hostile against {Subject.Name}";
    public string OptionCode => "H";
}

public record ExchangeInteraction: IInteraction {
    public ExchangeInteraction(IActor agent,
        IOffer agentOffer,
        IActor subject,
        IOffer subjectOffer,
        string optionCode,
        string? description = null,
        InteractionMode mode = InteractionMode.Menu) {
        Agent = agent;
        AgentOffer = agentOffer;
        Subject = subject;
        SubjectOffer = subjectOffer;
        OptionCode = optionCode;
        Description = description ?? MakeDescription();
        _mode = mode;
    }
    public IActor Agent { get; init; }
    public IActor Subject { get; init; }
    readonly InteractionMode _mode;

    public InteractionMode PerformMode(string args = "") {
        bool aoe = AgentOffer.EnabledFor(Agent, Subject);
        bool soe = SubjectOffer.EnabledFor(Subject, Agent);
        if (aoe && soe) {
            Debug.WriteLine($"Can {Description}: {_mode}");
            return _mode;
        } else {
            Debug.WriteLine($"Can {Description}: Bad " + (aoe ? "" : "Agent ") + (soe ? "" : "Subject "));
            return InteractionMode.Disabled;
        }
    }

    public int Perform(string args = "") {
        int count = 1;
        if (!string.IsNullOrWhiteSpace(args) && int.TryParse(args, out int parsed)) {
            count = Math.Max(1, parsed);
        }

        int performed = 0;
        for (int i = 0; i < count; i++) {
            if (PerformMode() == InteractionMode.Disabled) {
                break;
            }
            AgentOffer.PerformOn(Agent, Subject);
            SubjectOffer.PerformOn(Subject, Agent);
            performed++;
        }

        if (performed > 0) {
            Agent.Message($"You gave {Subject.Name} {AgentOffer.Description} and got {SubjectOffer.Description} in return. (x{performed})");
            Subject.Message($"You gave {Agent.Name} {SubjectOffer.Description} and got {AgentOffer.Description} in return. (x{performed})");
        }
        return performed;
    }
    public string Description { get; init; }
    public override string ToString() => Description;
    public IOffer AgentOffer { get; init; }
    public IOffer SubjectOffer { get; init; }
    public string OptionCode { get; init; }
    public string MakeDescription() {
        // Note: Can't access Value here without Agent binding
        var buyerDesc = AgentOffer.Description;
        var sellerDesc = SubjectOffer.Description;
        if (AgentOffer is EmptyOffer) {
            return $"{sellerDesc}";
        } else if (SubjectOffer is EmptyOffer) {
            return $"{buyerDesc}";
        } else if (AgentOffer is ScrapOffer) {
            return $"Sell {sellerDesc} for {buyerDesc}";
        } else if (SubjectOffer is ScrapOffer) {
            return $"Buy {buyerDesc} for {sellerDesc}";
        }
        return $"Give {sellerDesc} for {buyerDesc}";
    }

    public string? MessageFor(IActor viewer) => null;
}
